version: '2.1'
services:
  ms-tenpo-test:
#    build: .
    image: ceeconro/ms-tenpo-test
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=tenpo_user
      - POSTGRES_PASSWORD=tempouser
      - POSTGRES_DB=tenpotest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tenpo_user -d tenpotest"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
