version: '2.1'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=tenpo_user
      - POSTGRES_PASSWORD=tempouser
      - POSTGRES_DB=tenpotest
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
