version: '2.1'
services:
  ms-tenpo-test:
#    build: .
    image: ceeconro/ms-tenpo-test
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - kafka_merge_net
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=tenpo_user
      - POSTGRES_PASSWORD=tempouser
      - POSTGRES_DB=tenpotest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tenpo_user -d tenpotest" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - kafka_merge_net


  zookeeper:
    container_name:
      zookeeper_merge
    image:
      wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka_merge_net
    healthcheck:
      test: [ "CMD-SHELL", "echo ruok | nc -w 2 zookeeper 4444" ]
      interval: 5s
      timeout: 10s
      retries: 3
  kafka:
    container_name:
      kafka_merge
    image:
      wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ZK_SERVER: zookeeper:2181
      ADVERTISED_HOST: localhost
      CONSUMER_THREADS: 5
      BROKER_ID: 1
      ADVERTISED_PORT: 9092
    healthcheck:
      test:
        [ "CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181" ]
      interval: 30s
      timeout: 10s
      retries: 4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka_merge_net

networks:
  kafka_merge_net:
    driver: bridge

volumes:
  database:
