logging:
  level:
    root: DEBUG
    org.tenpo: DEBUG

api:
  common:
    version: 1.0.0
    title: Tenpo test
    description: API multiply numbers
    contact:
      name: Cesar Contreras
      url: https://github.com/ceeconro
      email: ceeconro@gmail.com
  ms-tenpo-test:
    multiply:
      description: multiply two numbers and return the result


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tenpotest
    username: tenpo_user
    password: tempouser
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: ms-tenpo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

message.topic.name: multiply-presist-topic
message.group.name: multiply_group

auth:
  jwt:
    issuer: "Tenpo"
    ttl-in-seconds: 3600
    secret: "ej7+D6Hh2r2KBEIuoGz1RGjtXooObzebSSxNm7yu2YSkEKv8aQmC2iYuxXLkKYKgT1210e5ZKMoY4XM0uQnkJkKGA01tBWZK+Pi3zX+nZvVNTJbZwRSOyZ2bm99exCq+z6ER5q5XWes1G9/sG5rp7kK9bL/NdNdU13HAFjJew6NwyxIxFH5VhXWwtgIJy+1KcJ9+3kq6uYNylrPC2U1h0xvR9qQzi1D2m9H8ZA=="

---
spring:
  config:
    activate:
      on-profile: docker

server.port: 8080

spring.datasource:
  url: jdbc:postgresql://postgres/tenpotest
#spring.kafka:
#  bootstrap-servers: kafka_merge